/* ================= 班次工具 ================= */
let TRIP_DOW=null,OT_AGG=null,TOOLS_INIT=false,CUT_ROWS=[],MG_ROWS=[],OT_ROWS=[];
const DOWS='一二三四五六日';
const dowOf=ymd=>DOWS[new Date(ymd.slice(0,4),+ymd.slice(4,6)-1,+ymd.slice(6)).getDay()===0?6:new Date(ymd.slice(0,4),+ymd.slice(4,6)-1,+ymd.slice(6)).getDay()-1];
async function initTools(){if(TOOLS_INIT)return;TOOLS_INIT=true;
 $$('#toolTabs button').forEach(b=>b.onclick=()=>{$$('#toolTabs button').forEach(x=>x.classList.toggle('pri',x===b));['cut','merge','trip','ot','review'].forEach(t=>$('#tool-'+t).classList.toggle('hide',t!==b.dataset.tool));if(b.dataset.tool==='ot'&&!OT_ROWS.length)otRun();if(b.dataset.tool==='review')rvRun()});
 const lISO=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);const tm=new Date(Date.now()+864e5);$('#cutDay').value=lISO(tm);
 const rv=new Date(Date.now()-30*864e5);$('#rvFrom').value=lISO(rv);$('#rvTo').value=lISO(new Date(Date.now()+7*864e5));
 ROWS.slice().reverse().forEach(r=>{const o=document.createElement('option');o.value=r.day;o.textContent=iso(r.day)+'('+r.dow+')';$('#mgDay').appendChild(o)});
 $('#cutRun').onclick=cutRun;$('#cutAll').onclick=()=>{$$('#cutTable input[type=checkbox]').forEach(c=>c.checked=true);cutSum()};$('#cutNone').onclick=()=>{$$('#cutTable input[type=checkbox]').forEach(c=>c.checked=false);cutSum()};
 $('#cutXls').onclick=()=>exportXlsx(CUT_COLS.map(c=>[c[0],c[1]]),CUT_ROWS,'減開建議_'+$('#cutDay').value);$('#cutSave').onclick=cutSave;$('#cutQ').oninput=()=>cutRender();
 $('#mgRun').onclick=mgRun;$('#mgXls').onclick=()=>exportXlsx(MG_COLS.map(c=>[c[0],c[1]]),MG_ROWS,'併櫃模擬_'+$('#mgDay').value);$('#mgSave').onclick=mgSave;$('#mgQ').oninput=()=>mgRender();
 $('#tpRun').onclick=()=>tripCard($('#tpCode').value.trim());$('#tpCode').onkeydown=e=>{if(e.key==='Enter')tripCard($('#tpCode').value.trim())};
 $('#otRun').onclick=otRun;$('#otXls').onclick=()=>exportXlsx(OT_COLS.map(c=>[c[0],c[1]]),OT_ROWS,'加班檢核');$('#otQ').oninput=()=>otRender();
 $('#rvRun').onclick=rvRun;
 try{const j=await api({action:'meta',k:'trip_dow'});TRIP_DOW=j.v||{};const dl=$('#tpList');Object.entries(TRIP_DOW).slice(0,4000).forEach(([c,t])=>{const o=document.createElement('option');o.value=c;o.label=t.name;dl.appendChild(o)})}catch(e){TRIP_DOW={};alert('班次統計載入失敗：'+e.message)}
 cutRun()}
/* ---- 減開建議清單 ---- */
const CUT_COLS=[['code','班次'],['name','名稱'],['route','起站→迄站'],['dir','方向'],['km','里程'],['recent','近期同星期積載率'],['low','低載/出現'],['avg','平均積載'],['allshare','全期低載比'],['save_km','可省 km/日'],['save_nt','可省 元/日'],['save_pp','可省 元/件']];
function forecastFor(dayIso){const w=DOWS[(new Date(dayIso).getDay()+6)%7];const list=ROWS.filter(r=>r.dow===w&&r.pieces&&r.day<dayIso.replace(/-/g,'')).slice(-4);if(!list.length)return {w,pieces:null,list:[]};return {w,pieces:list.reduce((a,b)=>a+b.pieces,0)/list.length,list}}
async function cutRun(){if(!TRIP_DOW)return;const dayIso=$('#cutDay').value;const fc=forecastFor(dayIso);const thr=$('#cutThr').value,win=$('#cutWin').value,min=+$('#cutMin').value,dir=$('#cutDir').value,noOt=$('#cutNoOt').checked,price=+$('#cutPrice').value;
 $('#cutFc').innerHTML=`星期${fc.w}　預測件數 <b>${fmt(fc.pieces)}</b>（近 4 週同星期：${fc.list.map(r=>iso(r.day).slice(5)+' '+fmt(r.pieces)).join('、')||'無資料'}）`;
 const rows=[];for(const [code,t] of Object.entries(TRIP_DOW)){const d=t.dow?.[fc.w];if(!d)continue;if(noOt&&t.ot_share>0.2)continue;if(dir&&t.dir!==dir)continue;
  const n=win==='all'?d.n:d['n'+win];const low=win==='all'?d['low'+thr]:d['low'+thr+'_'+win];const avg=win==='all'?d.avg:d['avg'+win];if(n==null||n<min||low<min)continue;
  const km=t.km||0;rows.push({code,name:t.name,route:`${t.from}→${t.to}`,dir:t.dir,km:t.km,recent:(d.recent||[]).map(x=>Math.round(x[1])).join(' / '),low:`${low}/${n}`,lowShare:low/n,avg,allshare:Math.round(d.low55/d.n*100)+'%',save_km:km,save_nt:Math.round(km*price),save_pp:fc.pieces?+(km*price/fc.pieces).toFixed(3):null,sortKey:low/n*1000+km})}
 rows.sort((a,b)=>b.lowShare-a.lowShare||(b.km||0)-(a.km||0));CUT_ROWS=rows;
 let adopted=new Set();try{const j=await api({action:'decide_list',from:dayIso,to:dayIso});if(j.rows.length){adopted=new Set(j.rows[0].adopted||[]);$('#cutNote').value=j.rows[0].note||'';$('#cutSaved').textContent=`已有登記（${(j.rows[0].updated_at||'').slice(0,16).replace('T',' ')}，採用 ${adopted.size} 班）`}else{$('#cutSaved').textContent='';$('#cutNote').value=''}}catch(e){}
 cutRender(adopted)}
function cutRender(adopted){const q=$('#cutQ').value.trim().toLowerCase();const prev=adopted||new Set($$('#cutTable input[type=checkbox]:checked').map(c=>c.value));const rows=CUT_ROWS.filter(r=>!q||(r.code+r.name+r.route).toLowerCase().includes(q));
 $('#cutTable').innerHTML=rows.length?'<table><thead><tr><th>採用</th>'+CUT_COLS.map(c=>`<th class="${['km','avg','save_km','save_nt','save_pp'].includes(c[0])?'num':''}">${c[1]}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>`<tr><td><input type="checkbox" value="${r.code}" ${prev.has(r.code)?'checked':''}></td>`+CUT_COLS.map(c=>{const v=r[c[0]];if(c[0]==='code')return `<td><a href="#" class="tp" data-c="${r.code}">${r.code}</a></td>`;if(['km','save_km','save_nt'].includes(c[0]))return `<td class="num">${fmt(v)}</td>`;if(c[0]==='avg')return `<td class="num">${fmt(v,1)}</td>`;if(c[0]==='save_pp')return `<td class="num">${v==null?'—':v.toFixed(3)}</td>`;return `<td>${esc(v)}</td>`}).join('')+'</tr>').join('')+'</tbody></table>':'<p class="note">沒有符合規則的班次</p>';
 $$('#cutTable input[type=checkbox]').forEach(c=>c.onchange=cutSum);$$('#cutTable a.tp').forEach(a=>a.onclick=ev=>{ev.preventDefault();openTrip(a.dataset.c)});cutSum()}
function cutSum(){const fc=forecastFor($('#cutDay').value);const price=+$('#cutPrice').value;const all=CUT_ROWS;const sel=new Set($$('#cutTable input[type=checkbox]:checked').map(c=>c.value));const pick=all.filter(r=>sel.has(r.code));const km=l=>l.reduce((a,b)=>a+(b.km||0),0);
 $('#cutTiles').innerHTML=[['候選班次',all.length,0],['候選合計里程',km(all),0],['候選可省元/日',km(all)*price,0],['採用班次',pick.length,0],['採用合計里程',km(pick),0],['採用可省元/日',km(pick)*price,0],['採用可省元/件',fc.pieces?km(pick)*price/fc.pieces:null,2],['無里程資料的候選',all.filter(r=>!r.km).length,0]].map(([k,v,d])=>`<div class="tile"><div class="k">${k}</div><div class="v">${fmt(v,d)}</div></div>`).join('')}
async function cutSave(){const dayIso=$('#cutDay').value;const fc=forecastFor(dayIso);const sel=$$('#cutTable input[type=checkbox]:checked').map(c=>c.value);$('#cutSave').disabled=true;try{let merges=[];try{const j=await api({action:'decide_list',from:dayIso,to:dayIso});if(j.rows.length)merges=j.rows[0].merges||[]}catch(e){}
 await api({action:'decide_save',day:dayIso,forecast:{pieces:fc.pieces,dow:fc.w,basis:fc.list.map(r=>[r.day,r.pieces])},params:{thr:$('#cutThr').value,win:$('#cutWin').value,min:+$('#cutMin').value,dir:$('#cutDir').value,noOt:$('#cutNoOt').checked,price:+$('#cutPrice').value},suggested:CUT_ROWS.map(r=>({code:r.code,name:r.name,route:r.route,dir:r.dir,km:r.km,low:r.low,avg:r.avg})),adopted:sel,merges,note:$('#cutNote').value});$('#cutSaved').textContent=`已登記 ${new Date().toLocaleString('zh-TW')}：建議 ${CUT_ROWS.length} 班、採用 ${sel.length} 班`}catch(e){alert(e.message)}finally{$('#cutSave').disabled=false}}
/* ---- 併櫃模擬 ---- */
const MG_COLS=[['mode','模式'],['from','起站'],['keep_name','保留班次'],['load_keep','保留積載'],['dep_keep','保留規定離站'],['to1','保留迄站'],['cut_name','併入班次'],['load_cut','併入積載'],['seal_cut','併入封櫃'],['to2','併入迄站'],['sum','合計'],['delay_min','延後(分)'],['dir','方向'],['cut_km','省 km'],['save_nt','省 元'],['cat','類別']];
async function mgRun(){const day=$('#mgDay').value;if(!day)return;$('#mgTable').innerHTML='<p class="note"><span class="spin"></span> 載入…</p>';try{if(!DETAIL[day]||!DETAIL[day].merge_pairs){const j=await api({action:'detail',day:iso(day),kinds:['merge_pairs']});DETAIL[day]=DETAIL[day]||{};j.rows.forEach(r=>DETAIL[day][r.kind]=r.payload)}
 const price=+$('#cutPrice').value||23;const mode=$('#mgMode').value,cap=+$('#mgCap').value,maxDelay=+$('#mgDelay').value,reg=$('#mgReg').checked,dir=$('#mgDir').value;
 MG_ROWS=(DETAIL[day].merge_pairs||[]).filter(p=>(!mode||p.mode===mode)&&p.sum<=cap&&(p.delay_min==null||p.delay_min<=maxDelay)&&(!reg||(p.cat_keep==='正班'&&p.cat_cut==='正班'))&&(!dir||p.dir===dir)&&p.from!==p.to1).map(p=>({...p,keep_name:`${p.keep} ${p.keep_name}`,cut_name:`${p.cut} ${p.cut_name}`,cat:`${p.cat_keep}/${p.cat_cut}`,save_nt:Math.round((p.cut_km||0)*price)}));
 let adopted=new Set();try{const j=await api({action:'decide_list',from:iso(day),to:iso(day)});if(j.rows.length){adopted=new Set((j.rows[0].merges||[]).map(m=>m.box_cut));$('#mgSaved').textContent=`已登記配對 ${adopted.size} 組`}else $('#mgSaved').textContent=''}catch(e){}
 mgRender(adopted)}catch(e){$('#mgTable').innerHTML='<p class="note">'+esc(e.message)+'</p>'}}
function mgRender(adopted){const q=$('#mgQ').value.trim().toLowerCase();const prev=adopted||new Set($$('#mgTable input[type=checkbox]:checked').map(c=>c.value));const rows=MG_ROWS.filter(r=>!q||(r.from+r.keep_name+r.cut_name+r.to1+r.to2).toLowerCase().includes(q));
 $('#mgTable').innerHTML=rows.length?'<table><thead><tr><th>採用</th>'+MG_COLS.map(c=>`<th>${c[1]}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>`<tr><td><input type="checkbox" value="${esc(r.box_cut)}" ${prev.has(r.box_cut)?'checked':''}></td>`+MG_COLS.map(c=>{const v=r[c[0]];if(c[0]==='keep_name'||c[0]==='cut_name'){const code=c[0]==='keep_name'?r.keep:r.cut;return `<td><a href="#" class="tp" data-c="${code}">${esc(v)}</a></td>`}if(['load_keep','load_cut','sum','cut_km','save_nt','delay_min'].includes(c[0]))return `<td class="num">${v==null?'—':fmt(v,c[0]==='sum'?1:0)}</td>`;return `<td>${esc(v)}</td>`}).join('')+'</tr>').join('')+'</tbody></table>':'<p class="note">無配對候選</p>';
 $$('#mgTable input[type=checkbox]').forEach(c=>c.onchange=mgSum);$$('#mgTable a.tp').forEach(a=>a.onclick=ev=>{ev.preventDefault();openTrip(a.dataset.c)});mgSum()}
function mgSum(){const day=$('#mgDay').value;const pieces=BY[day]?.pieces;const price=+$('#cutPrice').value||23;const sel=new Set($$('#mgTable input[type=checkbox]:checked').map(c=>c.value));const pick=MG_ROWS.filter(r=>sel.has(r.box_cut));const km=l=>l.reduce((a,b)=>a+(b.cut_km||0),0);
 $('#mgTiles').innerHTML=[['候選配對（=可省車次）',MG_ROWS.length,0],['A 同起迄',MG_ROWS.filter(r=>r.mode==='A').length,0],['B 同區多點',MG_ROWS.filter(r=>r.mode==='B').length,0],['候選可省 km',km(MG_ROWS),0],['候選可省 元',km(MG_ROWS)*price,0],['採用配對',pick.length,0],['採用可省 km',km(pick),0],['採用可省 元/件',pieces?km(pick)*price/pieces:null,3]].map(([k,v,d])=>`<div class="tile"><div class="k">${k}</div><div class="v">${fmt(v,d)}</div></div>`).join('')}
async function mgSave(){const day=$('#mgDay').value;const dayIso=iso(day);const sel=new Set($$('#mgTable input[type=checkbox]:checked').map(c=>c.value));const merges=MG_ROWS.filter(r=>sel.has(r.box_cut)).map(r=>({mode:r.mode,from:r.from,keep:r.keep,cut:r.cut,box_keep:r.box_keep,box_cut:r.box_cut,to1:r.to1,to2:r.to2,sum:r.sum,delay_min:r.delay_min,cut_km:r.cut_km}));$('#mgSave').disabled=true;
 try{let prev={};try{const j=await api({action:'decide_list',from:dayIso,to:dayIso});if(j.rows.length)prev=j.rows[0]}catch(e){}
 await api({action:'decide_save',day:dayIso,forecast:prev.forecast||{},params:prev.params||{},suggested:prev.suggested||[],adopted:prev.adopted||[],merges,note:prev.note||''});$('#mgSaved').textContent=`已登記 ${merges.length} 組配對（${new Date().toLocaleString('zh-TW')}）`}catch(e){alert(e.message)}finally{$('#mgSave').disabled=false}}
/* ---- 班次體檢卡 ---- */
function openTrip(code){$$('#tabs button').forEach(x=>x.classList.toggle('on',x.dataset.t==='tools'));['dash','tools','data','status','docs'].forEach(t=>$('#t-'+t).classList.toggle('hide',t!=='tools'));$$('#toolTabs button').forEach(x=>x.classList.toggle('pri',x.dataset.tool==='trip'));['cut','merge','trip','ot','review'].forEach(t=>$('#tool-'+t).classList.toggle('hide',t!=='trip'));$('#tpCode').value=code;tripCard(code);$('#tool-trip').scrollIntoView({behavior:'smooth'})}
async function tripCard(code){if(!code)return;const o=$('#tpOut');o.innerHTML='<p class="note"><span class="spin"></span> 載入…</p>';try{const j=await api({action:'trip_hist',code});if(!j.info){o.innerHTML='<p class="note">查無此班次（只收錄 2026-04 起有封櫃紀錄的班次）</p>';return}const info=j.info,hist=j.hist||{};const days=Object.keys(hist).sort();
 const prof=DOWS.split('').map(w=>{const ls=days.filter(d=>dowOf(d)===w).map(d=>hist[d].l);const ot=days.filter(d=>dowOf(d)===w&&/加班|追加/.test(hist[d].c)).length;return {w,n:ls.length,avg:ls.length?ls.reduce((a,b)=>a+b,0)/ls.length:null,low:ls.filter(x=>0<x&&x<=55).length,ot}});
 const W=560,H=160,L=36,T=10,B=22;const n=days.length;const x=i=>L+(W-L-10)*(n===1?.5:i/(n-1));const bw=Math.max(1.5,(W-L-10)/n*.7);let g=`<svg class="ch" viewBox="0 0 ${W} ${H}">`;[0,25,50,75,100].forEach(v=>{const y=T+(H-T-B)*(1-v/100);g+=`<line class="axis" x1="${L}" x2="${W-10}" y1="${y}" y2="${y}"/><text class="lbl" x="${L-4}" y="${y+3}" text-anchor="end">${v}</text>`});const y55=T+(H-T-B)*(1-55/100);g+=`<line x1="${L}" x2="${W-10}" y1="${y55}" y2="${y55}" stroke="var(--red)" stroke-dasharray="3 3"/>`;
 days.forEach((d,i)=>{const h=hist[d];const y=T+(H-T-B)*(1-Math.min(100,h.l)/100);const c=/加班|追加/.test(h.c)?'var(--orange)':(h.l<=55?'var(--red)':'var(--acc)');g+=`<rect x="${x(i)-bw/2}" y="${y}" width="${bw}" height="${H-B-y}" fill="${c}" opacity=".85"><title>${iso(d)}(${dowOf(d)}) ${h.l}% ${h.n}櫃 ${h.c}${h.d!=null?' 到著'+(h.d>0?'晚':'早')+Math.abs(h.d)+'分':''}</title></rect>`;if(i%Math.ceil(n/8)===0||i===n-1)g+=`<text class="lbl" x="${x(i)}" y="${H-B+12}" text-anchor="middle">${d.slice(4,6)}/${d.slice(6)}</text>`});g+='</svg>';
 const recent=days.slice(-30).reverse();
 o.innerHTML=`<div class="card"><h3><span class="rid" style="color:var(--acc)">${esc(code)}</span> ${esc(info.name)} <span class="muted small">${esc(info.master||'')}</span></h3>
 <dl class="kv"><dt>起迄</dt><dd>${esc(info.from)} → ${esc(info.to)}（${esc(info.dir)}；${esc(info.rfrom)}→${esc(info.rto)}）</dd><dt>里程</dt><dd>${info.km!=null?fmt(info.km)+' km（113 回填中位數）':'無資料'}</dd><dt>出現</dt><dd>${info.n_days} 天（${iso(info.first)} ～ ${iso(info.last)}）；加班比 ${Math.round(info.ot_share*100)}%</dd></dl>
 <div class="legend"><span><i style="background:var(--acc)"></i>正班 &gt;55%</span><span><i style="background:var(--red)"></i>≤55% 低載</span><span><i style="background:var(--orange)"></i>加班/追加</span><span>— 紅虛線 55%</span></div>${g}</div>
 <div class="grid2" style="margin-top:10px"><div class="card"><h3>星期別</h3><table><thead><tr><th>星期</th><th class="num">出現</th><th class="num">平均積載</th><th class="num">低載次數</th><th class="num">加班次</th></tr></thead><tbody>${prof.map(p=>`<tr><td>${p.w}</td><td class="num">${p.n}</td><td class="num">${fmt(p.avg,1)}</td><td class="num ${p.n&&p.low/p.n>=.5?'up':''}">${p.low}</td><td class="num">${p.ot}</td></tr>`).join('')}</tbody></table></div>
 <div class="card"><h3>最近 30 次</h3><div class="scroll" style="max-height:300px"><table><thead><tr><th>日期</th><th>週</th><th class="num">積載</th><th class="num">櫃</th><th>類別</th><th class="num">到著差(分)</th></tr></thead><tbody>${recent.map(d=>{const h=hist[d];return `<tr><td>${iso(d)}</td><td>${dowOf(d)}</td><td class="num ${h.l<=55?'up':''}">${h.l}</td><td class="num">${h.n}</td><td>${esc(h.c)}</td><td class="num">${h.d==null?'—':h.d}</td></tr>`}).join('')}</tbody></table></div></div></div>`}catch(e){o.innerHTML='<p class="note">'+esc(e.message)+'</p>'}}
/* ---- 加班檢核 ---- */
const OT_COLS=[['code','班次'],['name','名稱'],['route','起站→迄站'],['dir','方向'],['ot_days','加班天數'],['boxes','櫃數'],['low55','加班卻低載'],['avg','平均積載'],['dows','星期分布'],['last','最近'],['km','里程']];
async function otRun(){if(!OT_AGG){try{const j=await api({action:'meta',k:'ot_agg'});OT_AGG=j.v||{}}catch(e){OT_AGG={}}}const min=+$('#otMin').value,dir=$('#otDir').value,sort=$('#otSort').value;
 OT_ROWS=Object.entries(OT_AGG).filter(([c,t])=>t.ot_days>=min&&(!dir||t.dir===dir)).map(([code,t])=>({code,name:t.name,route:`${t.from}→${t.to}`,dir:t.dir,ot_days:t.ot_days,boxes:t.boxes,low55:t.low55,avg:t.avg,dows:DOWS.split('').map(w=>t.dow[w]?`${w}${t.dow[w]}`:'').filter(Boolean).join(' '),last:iso(t.last),km:t.km}));
 OT_ROWS.sort((a,b)=>sort==='avg'?a.avg-b.avg:b[sort]-a[sort]);otRender();
 const wk=DOWS.split('').map(w=>{const l=ROWS.filter(r=>r.dow===w&&r.ot_total!=null);return {w,n:l.length,ot:avgOf(l,'ot_total'),net:avgOf(l,'ot_net_south'),seal:avgOf(l,'seal_ot')}});
 $('#otDow').innerHTML='<table><thead><tr><th>星期</th><th class="num">天數</th><th class="num">加班台數(83)</th><th class="num">加班櫃(205)</th><th class="num">南向−北向</th></tr></thead><tbody>'+wk.map(p=>`<tr><td>${p.w}</td><td class="num">${p.n}</td><td class="num">${fmt(p.ot,1)}</td><td class="num">${fmt(p.seal,1)}</td><td class="num ${p.net>0?'up':''}">${fmt(p.net,1)}</td></tr>`).join('')+'</tbody></table>';
 const imb=ROWS.slice(-60).filter(r=>Math.abs(r.ot_net_south||0)>=8).reverse();$('#otImb').innerHTML=imb.length?'<table><thead><tr><th>日期</th><th>週</th><th class="num">南向</th><th class="num">北向</th><th class="num">淨額</th><th class="num">每千件里程</th></tr></thead><tbody>'+imb.map(r=>`<tr><td>${iso(r.day)}</td><td>${r.dow}</td><td class="num">${r.ot_south}</td><td class="num">${r.ot_north}</td><td class="num ${r.ot_net_south>0?'up':'down'}">${r.ot_net_south>0?'+':''}${r.ot_net_south}</td><td class="num">${fmt(r.km_per_kpiece,1)}</td></tr>`).join('')+'</tbody></table>':'<p class="note">無</p>'}
function otRender(){const q=$('#otQ').value.trim().toLowerCase();const rows=OT_ROWS.filter(r=>!q||(r.code+r.name+r.route).toLowerCase().includes(q));$('#otTable').innerHTML=rows.length?'<table><thead><tr>'+OT_COLS.map(c=>`<th>${c[1]}</th>`).join('')+'</tr></thead><tbody>'+rows.slice(0,800).map(r=>'<tr>'+OT_COLS.map(c=>{const v=r[c[0]];if(c[0]==='code')return `<td><a href="#" class="tp" data-c="${r.code}">${r.code}</a></td>`;if(['ot_days','boxes','low55','km'].includes(c[0]))return `<td class="num ${c[0]==='low55'&&v>=3?'up':''}">${fmt(v)}</td>`;if(c[0]==='avg')return `<td class="num">${fmt(v,1)}</td>`;return `<td>${esc(v)}</td>`}).join('')+'</tr>').join('')+'</tbody></table>':'<p class="note">無資料</p>';$$('#otTable a.tp').forEach(a=>a.onclick=ev=>{ev.preventDefault();openTrip(a.dataset.c)})}
/* ---- 決策回看 ---- */
async function rvRun(){const t=$('#rvTable');t.innerHTML='<p class="note"><span class="spin"></span> 載入…</p>';try{const j=await api({action:'decide_list',from:$('#rvFrom').value,to:$('#rvTo').value});if(!j.rows.length){t.innerHTML='<p class="note">這段期間沒有登記</p>';return}
 const out=[];for(const d of j.rows){const ymd=d.day.replace(/-/g,'');const r=BY[ymd];const i=ROWS.indexOf(r);const base=i>=0?ROWS.slice(Math.max(0,i-28),i).filter(x=>x.dow===r.dow):[];const bk=avgOf(base,'km_per_kpiece');
  let notRun=null;if(r&&(d.adopted||[]).length){notRun=0;for(const code of d.adopted.slice(0,40)){try{const h=await api({action:'trip_hist',code});if(h.hist&&!h.hist[ymd])notRun++}catch(e){}}}
  out.push({day:d.day,dow:r?r.dow:DOWS[(new Date(d.day).getDay()+6)%7],fc:d.forecast?.pieces,act:r?.pieces,sug:(d.suggested||[]).length,adp:(d.adopted||[]).length,rate:(d.suggested||[]).length?Math.round((d.adopted||[]).length/d.suggested.length*100):null,notRun,mg:(d.merges||[]).length,mgkm:(d.merges||[]).reduce((a,b)=>a+(b.cut_km||0),0),kpp:r?.km_per_kpiece,bk,er:r?.empty_rate,ot:r?.arrive_ontime_rate,by:d.by_emp,note:d.note,at:d.updated_at?new Date(d.updated_at).toLocaleString('zh-TW',{hour12:false}).slice(0,16):''})}
 t.innerHTML='<table><thead><tr><th>目標日</th><th>週</th><th class="num">預測件數</th><th class="num">實際件數</th><th class="num">建議班</th><th class="num">採用班</th><th class="num">執行率</th><th class="num">實際未開</th><th class="num">併櫃組</th><th class="num">併櫃省km</th><th class="num">每千件里程</th><th class="num">同星期基準</th><th class="num">空駛率</th><th class="num">到著準點率</th><th>登記</th><th>備註</th><th></th></tr></thead><tbody>'+out.map(o=>`<tr><td>${o.day}</td><td>${o.dow}</td><td class="num">${fmt(o.fc)}</td><td class="num">${fmt(o.act)}</td><td class="num">${o.sug}</td><td class="num">${o.adp}</td><td class="num">${o.rate==null?'—':o.rate+'%'}</td><td class="num">${o.notRun==null?'—':o.notRun}</td><td class="num">${o.mg}</td><td class="num">${fmt(o.mgkm)}</td><td class="num ${o.kpp&&o.bk?(o.kpp<o.bk?'down':'up'):''}">${fmt(o.kpp,1)}</td><td class="num">${fmt(o.bk,1)}</td><td class="num">${fmt(o.er,1)}</td><td class="num">${fmt(o.ot,1)}</td><td>${esc(o.by)} ${esc(o.at)}</td><td style="white-space:normal">${esc(o.note)}</td><td><a href="#" class="rvdel" data-d="${o.day}">清除</a></td></tr>`).join('')+'</tbody></table><p class="note">實際件數／每千件里程／空駛率要等該日資料同步後才會出現；「實際未開」＝採用班次在該日封櫃明細查無（最多檢查前 40 班）。</p>';$$('#rvTable a.rvdel').forEach(a=>a.onclick=async ev=>{ev.preventDefault();if(!confirm(a.dataset.d+' 的登記要清除嗎？'))return;try{await api({action:'decide_delete',day:a.dataset.d});rvRun()}catch(e){alert(e.message)}})}catch(e){t.innerHTML='<p class="note">'+esc(e.message)+'</p>'}}
